package karn.minecraftsnap.config;

import java.util.List;

public class TextConfigFile {
	private static final String LEGACY_BOSS_BAR_TEMPLATE = "&c레드 {red_score} &8| &f남은 시간 {time} &8| &9블루 {blue_score}";
	private static final String LEGACY_CAPTAIN_HUD_TEMPLATE = "&d다음 소환 &f{player} &8| &e라인 &f{lane}";
	public String prefix = "&7[&6!&7]&f ";
	public String bossBarTemplate = "&c레드 &f{red_score} &8| &f⌛{time} &8| &e다음 라인 공개: &f{next_reveal_time} &8| &9블루 &f{blue_score}";
	public String bossBarTitle = "&fMCsnap";
	public String teamChatFormat = "&8[&a팀&8] &7[{team} / {role}] &f{player}&7: {message}";
	public String teamChatNoTeamMessage = "&c팀 채팅은 팀 배정 이후에만 사용할 수 있음";
	public String teamChatEmptyMessage = "&c팀 채팅 내용이 비어있음";
	public String factionSelectBossBarTemplate = "&6팩션 선택 남은 시간 &f{time}";
	public String closedLaneMessage = "&c아직 공개되지 않은 라인임";
	public String ladderPrefixFormat = "[{ladder}] ";
	public String captainStar = "★ ";
	public String unitHudTemplate = "&f{unit} &8| &b{skill} &8| {cooldown}";
	public String unitHudReadyMessage = "&a준비 완료";
	public String unitHudCooldownTemplate = "&e{seconds}초";
	public String unitHudFallbackSkillName = "기본 스킬";
	public String unitHudUnknownUnitName = "알 수 없는 유닛";
	public String captainHudTemplate = "&b{current_mana}&7/&f{max_mana} &8({mana_cooldown}초) &8| &e{lane} &8| &d{player} &8| &c{skill_cooldown}초";
	public String captainHudNoTargetPlayerName = "대기 중 없음";
	public String spectatorQueueHudTemplate = "&7소환 대기열: &f{position}번";
	public String captureDefaultBossBarText = "&f점령";
	public String captureContestedBossBarText = "&e격돌중!";
	public String captureRedOwnerBossBarText = "레드 점령지";
	public String captureBlueOwnerBossBarText = "블루 점령지";
	public String captureNeutralOwnerBossBarText = "중립 점령지";
	public String captureProgressBossBarTemplate = "&f{owner} &8| &e{current}&7/&f{required}";
	public String captureOwnerChangedBroadcastTemplate = "&e{lane} 점령지 -> {owner}";
	public String captureLane1Name = "1라인";
	public String captureLane2Name = "2라인";
	public String captureLane3Name = "3라인";
	public String captureOwnerRedName = "&c레드";
	public String captureOwnerBlueName = "&9블루";
	public String captureOwnerNeutralName = "&f중립";
	public String lobbyPhaseMessage = "&e로비로 복귀";
	public String teamSelectPhaseMessage = "&a팀 배정 시작";
	public String factionSelectPhaseMessage = "&6팩션 선택 시작";
	public String gameStartPhaseMessage = "&b게임 준비 시작";
	public String gameRunningPhaseMessage = "&c게임 시작";
	public String gameEndPhaseMessage = "&d게임 종료";
	public String factionSelectionMessage = "&f{team} 팀 사령관이 &6{faction} &f팩션 선택";
	public String villagerFactionName = "주민";
	public String monsterFactionName = "몬스터";
	public String netherFactionName = "네더";
	public String advanceNotAvailableMessage = "&c아직 전직할 수 없음";
	public String advanceReadyMessage = "&a전직 가능 상태가 됨";
	public String gameEndTitleTemplate = "&6승리: &f{winner}";
	public String gameEndDrawTitleTemplate = "&e무승부";
	public String captainSpawnGuiTitle = "&6유닛 소환";
	public String captainSpawnNoFactionMessage = "&c팩션이 정해지지 않았음";
	public String captainSpawnBlockedLaneMessage = "&c{lane}은 아직 공개되지 않아 소환 불가";
	public String gameStartCountdownTitle = "&e게임 시작";
	public String gameStartCountdownSubtitleTemplate = "&f{seconds}초";
	public String victoryCountdownSubtitleTemplate = "&e{team} 팀 승리 임박 &7({seconds}초)";
	public String customDeathMessage = "&8[사망] &f{victim} &7사망";
	public String customDeathMessageWithAttacker = "&8[사망] &f{victim} &7사망 &8(공격자: &f{attacker}&8)";
	public String autoStartEnabledMessage = "&a팀 선택 자동 시작: &f켜짐";
	public String autoStartDisabledMessage = "&c팀 선택 자동 시작: &f꺼짐";
	public String mainLobbyTitle = "&0메인 UI";
	public String mainLobbyCaptainPreferenceName = "&6사령관 선호";
	public List<String> mainLobbyCaptainPreferenceLore = List.of("&7사령관 우선 배정 설정", "{state}");
	public String mainLobbyCaptainPreferenceEnabledLore = "&a현재 활성화됨";
	public String mainLobbyCaptainPreferenceDisabledLore = "&8현재 비활성화됨";
	public String mainLobbyStatsName = "&e개인 통계";
	public List<String> mainLobbyStatsLore = List.of(
		"&7점수: &b{score}",
		"&7승률: &f{win_rate}",
		"&7플레이 횟수: &f{games}",
		"&7사령관 횟수: &f{captain_games}",
		"&7평균 점령 포인트: &f{average_capture}",
		"&7K/D: &f{kd} &8({kills}/{deaths})"
	);
	public String mainLobbyRulesName = "&e게임 설명";
	public List<String> mainLobbyRulesLore = List.of("&7클릭해서 게임 규칙 확인");
	public String mainLobbyUnitGuideName = "&a유닛 도감";
	public List<String> mainLobbyUnitGuideLore = List.of("&7클릭해서 유닛 정보 확인");
	public String mainLobbyBiomeGuideName = "&2바이옴 도감";
	public List<String> mainLobbyBiomeGuideLore = List.of("&7클릭해서 바이옴 정보 확인");
	public String mainLobbyAdminToolsName = "&c관리자 도구";
	public String mainLobbyCloseName = "&c닫기";
	public String adminToolsGuiTitle = "&0관리자 도구";
	public String adminToolsAssignTeamsName = "&5팀 배정";
	public String adminToolsClearTeamsName = "&f팀 해제";
	public String adminToolsFactionSelectName = "&d팩션 선택";
	public String adminToolsGameEndName = "&c게임 종료";
	public String adminToolsCloseName = "&c닫기";
	public String adminToolsFactionSelectBlockedMessage = "&c먼저 팀 배정을 완료해야 합니다";
	public String lobbyScoreboardTitle = "&6마크스냅";
	public String lobbyScoreboardPhaseTemplate = "&f페이즈: &e{phase}";
	public String lobbyScoreboardPlayerTemplate = "&f{rank}. &e{player} &7- &b{ladder}";
	public String lobbyScoreboardWikiHint = "&7/mcsnap wiki 로 안내 확인";
	public String wikiMainTitle = "&6MCsnap 위키";
	public String wikiOverviewName = "&e게임 개요";
	public List<String> wikiOverviewLore = List.of(
		"&73개 라인의 점령지를 두고 싸우는 RTS형 미니게임입니다.",
		"&7라인은 시간이 지나면서 순서대로 공개됩니다.",
		"&7시간 종료 시 점수가 높은 팀이 승리합니다."
	);
	public String wikiCommanderName = "&f사령관 설명";
	public List<String> wikiCommanderLore = List.of(
		"&7사령관은 유닛을 소환해 라인으로 보냅니다.",
		"&7라인 공개와 시간 경과에 따라 마나를 회복합니다.",
		"&7팩션별 전용 스킬을 사용할 수 있습니다."
	);
	public String wikiOverviewPhaseLoreTemplate = "&f현재 페이즈: &a{phase}";
	public String wikiOverviewRuleLore = "&79분 동안 3개 라인의 점령 점수 경쟁";
	public String wikiOverviewHintLore = "&7Shift+F로 상황별 GUI 열기";
	public String wikiFactionButtonName = "&a팩션";
	public List<String> wikiFactionButtonLore = List.of("&7팩션별 요약과 사령관 스킬 확인");
	public String wikiFactionButtonLore1 = "&7주민&우민 / 몬스터 / 네더";
	public String wikiFactionButtonLore2 = "&7요약과 사령관 스킬 설명 보기";
	public String wikiUnitButtonName = "&c유닛";
	public List<String> wikiUnitButtonLore = List.of("&7팩션별 유닛과 전직 정보 확인");
	public String wikiUnitButtonLore1 = "&7팩션별 유닛 목록과 상세 보기";
	public String wikiUnitButtonLore2 = "&7전직 유닛도 포함";
	public String wikiBiomeButtonName = "&2바이옴";
	public List<String> wikiBiomeButtonLore = List.of("&7출현 가능한 바이옴과 효과 확인");
	public String wikiBiomeButtonLore1 = "&7출현 가능한 바이옴 목록";
	public String wikiBiomeButtonLore2 = "&7공개 메시지와 설명 확인";
	public String wikiFactionIndexTitle = "&a팩션 도감";
	public String wikiUnitIndexTitle = "&c유닛 도감";
	public String wikiBiomeIndexTitle = "&2바이옴 도감";
	public String wikiFactionUnitListTitleTemplate = "&f{faction} 유닛";
	public String wikiSummaryName = "&f개요";
	public String wikiBackName = "&e뒤로";
	public String wikiBackFactionLore = "&7팩션 목록으로 복귀";
	public String wikiBackUnitFactionLore = "&7유닛 분류로 복귀";
	public String wikiBackUnitListLore = "&7이전 유닛 목록으로 복귀";
	public String wikiBackBiomeLore = "&7바이옴 목록으로 복귀";
	public String wikiHomeName = "&6위키 메인";
	public String wikiHomeLore = "&7위키 첫 화면으로 복귀";
	public String wikiNoDataLore = "&7데이터 없음";
	public String wikiVillagerCategoryName = "&a주민&우민";
	public String wikiVillagerCategoryLore = "&7주민 계열 유닛 보기";
	public String wikiMonsterCategoryName = "&c몬스터";
	public String wikiMonsterCategoryLore = "&7몬스터 및 전직 유닛 보기";
	public String wikiNetherCategoryName = "&6네더";
	public String wikiNetherCategoryLore = "&7네더 유닛 보기";
	public String preparationGuiTitle = "&6게임 준비";
	public String preparationToggleLore = "&7클릭해서 우선 배정 토글";
	public String preparationReadonlyLore = "&7사령관은 읽기 전용";
	public String preparationCostLoreTemplate = "&7코스트: &b{cost}";
	public String preparationSelectedLore = "&a현재 우선 배정됨";
	public String preparationUnselectedLore = "&8미선택";
	public String advanceGuiTitle = "&c전직";
	public String advanceNoOptionName = "&c전직 대상 없음";
	public String advanceNoOptionLore = "&7현재 유닛은 전직 옵션이 없음";
	public String advanceConditionPrefix = "&7조건: &f";
	public String advanceConditionBiomeDurationLoreTemplate = "&7조건: &f{biomes}&7에서 &f{seconds}초&7 동안 잔류";
	public String advanceConditionBiomeWeatherDurationLoreTemplate = "&7조건: &f{biomes}&7에서 &f{weather}&7 상태로 &f{seconds}초&7 동안 잔류";
	public String advanceConditionWeatherDurationLoreTemplate = "&7조건: &f{weather}&7 상태로 &f{seconds}초&7 동안 잔류";
	public String advanceConditionBiomeDurationSuffixTemplate = "&7에서 &f{seconds}초&7 동안 잔류";
	public String advanceConditionBiomeWeatherDurationSuffixTemplate = "&7에서 &f{weather}&7 상태로 &f{seconds}초&7 동안 잔류";
	public String advanceProgressLoreTemplate = "&7진행도: &b{current}&7/&f{required}";
	public String advanceConditionUnmetLore = "&c조건이 충족되지 않음";
	public String advanceWaitingLore = "&e잔류 중";
	public String advanceClickLore = "&a클릭해서 전직";
	public String advanceBroadcastMessage = "&d전직: &f{player} &7-> &a{unit}";
	public String advanceCompleteMessage = "&a전직 완료: &f{unit}";
	public String unitSpawnedMessage = "&a소환됨: &f{unit}";
	public String unitSpawnCaptainOnlyMessage = "&c사령관만 소환 가능";
	public String unitSpawnUnknownUnitMessage = "&c알 수 없는 유닛";
	public String unitSpawnWrongFactionMessage = "&c현재 팩션에서 소환 불가";
	public String unitSpawnNoCandidateMessage = "&c소환 가능한 관전자 유닛 없음";
	public String unitSpawnInsufficientManaMessage = "&c마나가 부족함";
	public String unitSpawnTargetMissingMessage = "&c대상 유닛 플레이어를 찾지 못함";
	public String captainSpawnSuccessMessage = "&a유닛 소환 완료: &f{player} &7-> &f{unit}";
	public String captainSpawnCostLoreTemplate = "&7코스트: &b{cost}";
	public String captainSpawnCooldownLoreTemplate = "&7생성 쿨다운: &e{seconds}초";
	public String captainSpawnHealthLoreTemplate = "&7체력: &c{health}";
	public String captainSpawnReadyLore = "&a클릭해서 소환";
	public String captainSpawnBlockedLore = "&c현재 소환 불가";
	public String factionSelectionRedTitle = "&c레드 팩션 선택";
	public String factionSelectionBlueTitle = "&9블루 팩션 선택";
	public String factionSelectionCaptainSkillLoreTemplate = "&8사령관 스킬: &d{skill}";
	public String factionSelectionSelectedLore = "&a현재 선택됨";
	public String factionSelectionClickLore = "&e클릭해서 선택";
	public String tradePurchaseSuccessMessage = "&a구매 완료";
	public String tradeInsufficientFundsMessage = "&c재화가 부족함";
	public String tradeInventoryFullMessage = "&c인벤토리 공간 부족";
	public String tradeInvalidEntryMessage = "&c상점 품목 설정 오류";
	public String tradeUnsupportedFactionMessage = "&c이 팩션은 상점을 사용할 수 없음";
	public String tradeVillagerTitle = "&a주민 상점";
	public String tradeVillagerEnchantTitle = "&a주민 강화 상점";
	public String tradeNetherTitle = "&6네더 상점";
	public String tradePriceLoreTemplate = "&f가격: {color}{price}";
	public String tradeClickLore = "&7클릭해서 구매";
	public String tradeMaxLevelMessage = "&c이미 최대 레벨";
	public String tradeNoEligibleEquipmentMessage = "&c강화 가능한 장비가 없음";
	public String tradeEnchantTargetLoreTemplate = "&7대상: {target}";
	public String tradeEnchantCurrentLoreTemplate = "&7현재: {label} {level}";
	public String tradeEnchantNextLoreTemplate = "&7다음: {label} {level}";
	public String tradeEnchantMaxLore = "&6최대 레벨";
	public String captainMenuItemName = "&e유닛 소환";
	public String captainMenuItemUseLore = "&7우클릭으로 소환 GUI 열기";
	public String captainMenuItemFactionLoreTemplate = "&8현재 팩션: &f{faction}";
	public String captainSkillItemName = "&d사령관 스킬";
	public String captainSkillItemUseLore = "&7우클릭으로 팩션 전용 사령관 능력 발동";
	public String captainSkillItemFactionLoreTemplate = "&8현재 팩션: &f{faction}";
	public String captainSkillCooldownMessage = "&c사령관 스킬 쿨다운: &f{seconds}초";
	public String captainSkillActivatedMessage = "&d사령관 스킬 발동";
	public String captainSkillInsufficientManaMessage = "&c사령관 마나가 부족함";
	public String captainVillagerSuccessMessage = "&a습격 소집 발동: &f{lane}";
	public String captainVillagerNoTargetMessage = "&c소집할 다른 라인 아군 유닛이 없음";
	public String captainMonsterWeatherGuiTitle = "&5날씨 변화";
	public String captainMonsterWeatherClearName = "맑음";
	public String captainMonsterWeatherRainName = "비";
	public String captainMonsterWeatherThunderName = "천둥";
	public String captainMonsterWeatherClearLore = "&7다음 변경 전까지 현재 날씨 유지";
	public String captainMonsterWeatherRainLore = "&72분 유지, 5초마다 아군 신속 I";
	public String captainMonsterWeatherThunderLore = "&760초 유지, 3초마다 회복/신속, 낮은 확률 번개";
	public String captainMonsterWeatherRemainingLoreTemplate = "&7남은 시간: &f{seconds}초";
	public String captainMonsterWeatherPersistentLore = "&7다음 변경 전까지 유지";
	public String captainMonsterWeatherActiveLore = "&a현재 활성화됨";
	public String captainMonsterWeatherClickLore = "&7클릭해서 변경";
	public String captainMonsterWeatherSuccessMessage = "&a날씨 변화 발동: &f{weather}";
	public String captainNetherPortalSuccessMessage = "&a포탈 생성: &f{lane}";
	public String captainPortalRefundMessage = "&6포탈 환급 &7(마나 +{mana})";
	public String adminForceUnitMessage = "&e관리자 유닛 강제 배정: &f{unit}";
	public String adminBotsSuccessMessage = "&a봇 생성 완료: &f{count}";
	public String adminBotsPartialMessage = "&c일부 봇만 생성됨 &7({created}/{requested})";
	public String adminBotsInvalidCountMessage = "&c봇 수는 1 이상이어야 함";
	public String commandRootReadyMessage = "&fMCsnap 명령 트리 준비 완료";
	public String commandReloadMessage = "&aMCsnap 컨픽 리로드 완료";
	public String commandSourceNotFoundMessage = "&c명령 실행 소스를 찾지 못함";
	public String commandPlayerNotFoundMessage = "&c플레이어를 찾지 못함";
	public String commandPreferenceUpdatedMessage = "&a선호 직업 갱신: &f{preference}";
	public String commandAssignCaptainMessage = "&a{player} 님을 {team} 사령관으로 지정 완료";
	public String commandTeamSelectionMessage = "&a팀 배정과 사령관 선출 완료 &7(자동 진행 없음)";
	public String commandForceStartMessage = "&a기본값 보정 후 게임 강제 시작";
	public String commandPhaseChangedMessage = "&a현재 페이즈: &f{phase}";
	public String commandLaneStateMessage = "&a{lane} 상태: &f{state}";
	public String commandForceUnitSuccessMessage = "&a유닛 강제 배정 완료: &f{unit}";
	public String commandPlaceNearestPlayerOnlyMessage = "&c플레이어만 가장 가까운 라인 구조물 설치 가능";
	public String commandPlaceNearestNoBiomeMessage = "&c{lane}에 배정된 바이옴이 없음";
	public String commandPlaceNearestMissingStructureMessage = "&c{lane}의 structureId 가 비어 있음";
	public String commandPlaceNearestSuccessMessage = "&a{lane} 구조물 설치 완료: &f{structure}";
	public String commandPlaceNearestFailureMessage = "&c{lane} 구조물 설치 실패";
	public String commandServerNotBoundMessage = "&c서버가 아직 바인딩되지 않음";
	public String commandResetStructuresSuccessMessage = "&a모든 라인 구조물을 minecraft:default 로 초기화 완료";
	public String commandResetStructuresPartialMessage = "&c일부 라인 구조물 초기화 실패 (&f{success}&7/&f{total}&c)";
	public String commandChargeManaFailedMessage = "&c사령관이 아니라 마나 충전 불가";
	public String commandChargeManaSuccessMessage = "&a사령관 마나 전충전: &f{player}";
	public String commandCaptainSkillFailedMessage = "&c해당 팩션 사령관 스킬 발동 실패";
	public String commandCaptainSkillSuccessMessage = "&a{faction} 팩션 사령관 스킬 강제 발동";
	public String commandAdvanceFailedMessage = "&c전직 가능 상태 강제 부여 실패";
	public String commandAdvanceSuccessMessage = "&a전직 가능 상태 강제 부여: &f{player}";
	public String commandOpenGuiPlayerOnlyMessage = "&c플레이어만 GUI 오픈 가능";
	public String commandOpenMainSuccessMessage = "&a메인 GUI 오픈";
	public String commandOpenWikiSuccessMessage = "&a위키 GUI 오픈";
	public String commandOpenUnitIndexSuccessMessage = "&a유닛 도감 GUI 오픈";
	public String commandOpenBiomeIndexSuccessMessage = "&a바이옴 도감 GUI 오픈";
	public String commandOpenAdminToolsSuccessMessage = "&a관리자 도구 GUI 오픈";
	public String commandOpenFactionSuccessMessage = "&a팩션 GUI 오픈";
	public String commandOpenPreparationSuccessMessage = "&a준비 GUI 오픈";
	public String commandOpenCaptainSpawnSuccessMessage = "&a사령관 소환 GUI 오픈";
	public String commandOpenTradeSuccessMessage = "&a거래 GUI 오픈";
	public String commandOpenAdvanceSuccessMessage = "&a전직 GUI 오픈";
	public String commandUnsupportedGuiMessage = "&c지원하지 않는 GUI";
	public String commandClearTeamsMessage = "&a팀 배정을 모두 해제했습니다";
	public String commandTimeAdjustedMessage = "&a경기 시간 조정: &f{ticks}틱 &7(남은 시간 {time}, {remaining_ticks}틱)";
	public String commandStatPlayerTemplate = "&f플레이어: &e{player}";
	public String commandStatLadderTemplate = "&f래더: &b{ladder} &8/ &f선호: &d{preference}";
	public String commandStatCombatTemplate = "&f킬: &a{kills} &8/ &f데스: &c{deaths} &8/ &f점령: &6{captures}";
	public String commandStatCurrencyTemplate = "&f에메랄드: &a{emeralds} &8/ &f금괴: &6{gold}";
	public String midMatchJoinAvailableMessage = "&7[&6!&7]&f /중참 명령어를 통해 진행중인 게임에 참여할 수 있습니다.";
	public String midMatchJoinUnavailableMessage = "&c게임 진행 중에만 중도 참여할 수 있습니다";
	public String midMatchJoinAlreadyJoinedMessage = "&c이미 진행 중인 게임에 참가 중입니다";
	public String midMatchJoinSuccessMessage = "&a중도 참여 완료: &f{team}&a 팀 유닛으로 배정되었습니다";
	public String surrenderVoteUnavailableMessage = "&c게임 진행 중에만 항복할 수 있습니다";
	public String surrenderVoteNoTeamMessage = "&c팀 배정 후에만 항복할 수 있습니다";
	public String surrenderVoteDuplicateMessage = "&c이미 항복 투표에 참여했습니다";
	public String surrenderVoteProgressMessage = "&7[&6!&7]&f 팀원이 항복에 동의했습니다. (&e{current}&7/&f{required}&f)";
	public String environmentAttackerName = "환경";
	public String creeperSelfDestructPrimedMessage = "&c자폭 준비";
	public String runningSidebarLaneTemplate = "{icon} &f({biome})";
	public String runningSidebarHiddenBiomeName = "???";
	public String runningSidebarNeutralIcon = "&f⬛";
	public String runningSidebarContestedIcon = "&e⬛";
	public String runningSidebarRedIcon = "&c⬛";
	public String runningSidebarBlueIcon = "&9⬛";
	public java.util.Map<String, java.util.List<String>> factionSummaries = new java.util.LinkedHashMap<>();
	public java.util.Map<String, java.util.List<String>> captainSkillDescriptions = new java.util.LinkedHashMap<>();
	public transient java.util.Map<String, java.util.List<String>> unitDescriptions = new java.util.LinkedHashMap<>();

	{
		factionSummaries.put("VILLAGER", java.util.List.of("&7주민과 우민 유닛을 사용합니다.", "&7유닛은 점령을 통해 에메랄드를 얻고", "&7상점을 이용할 수 있습니다."));
		factionSummaries.put("MONSTER", java.util.List.of("&7몬스터 유닛을 사용합니다.", "&7유닛은 위치한 바이옴에 적응하여 전직할 수 있습니다."));
		factionSummaries.put("NETHER", java.util.List.of("&7네더 유닛을 사용합니다.", "&7유닛은 적을 처치하여 금괴를 얻고", "&7상점을 이용할 수 있습니다."));

		captainSkillDescriptions.put("VILLAGER", java.util.List.of("&7다른 라인의 아군 유닛을 사령관이 있는 라인으로 소집합니다.", "&7유닛은 체력을 모두 회복하고, 재생, 신속, 성급함이 부여됩니다."));
		captainSkillDescriptions.put("MONSTER", java.util.List.of("&7맑음 / 비 / 폭풍우 선택합니다.", "&7비와 폭풍우는 아군 유닛을 버프하며", "&7폭풍우는 적에게 낮은 확률로 피해를 입힙니다."));
		captainSkillDescriptions.put("NETHER", java.util.List.of("&7가장 가까운 라인에 포탈을 생성합니다.", "&7해당 라인에 있는 아군은 힘을 얻고, 유닛 소환시 소모한 마나의 일부를 환급받습니다."));

		unitDescriptions.put("villager", java.util.List.of("&7체력 3 회복", "&7기본 유지력 유닛"));
		unitDescriptions.put("armorer_villager", java.util.List.of("&7방패와 흉갑 보유", "&7전선 유지용"));
		unitDescriptions.put("vindicator", java.util.List.of("&7짧은 돌진 스킬", "&7근접 압박용"));
		unitDescriptions.put("pillager", java.util.List.of("&73발 폭죽 지급", "&7원거리 견제용"));
		unitDescriptions.put("zombie", java.util.List.of("&7사망 시 아군 사령관 소환 쿨 2초 감소"));
		unitDescriptions.put("skeleton", java.util.List.of("&74칸 내 적에게 피해 5와 넉백"));
		unitDescriptions.put("slime", java.util.List.of("&7사망 시 사이즈 2 슬라임 3마리"));
		unitDescriptions.put("creeper", java.util.List.of("&71초 뒤 자폭", "&7근접 폭발 특화"));
		unitDescriptions.put("husk", java.util.List.of("&7공격 시 구속 I, 나약함 I 3초"));
		unitDescriptions.put("drowned", java.util.List.of("&7수중 호흡 무한, 물속 이동 강화"));
		unitDescriptions.put("stray", java.util.List.of("&7공격 시 구속 II 3초"));
		unitDescriptions.put("bogged", java.util.List.of("&7공격 시 독 III 5초"));
		unitDescriptions.put("wither_skeleton", java.util.List.of("&7공격 시 시듦 II 4초"));
		unitDescriptions.put("giant_slime", java.util.List.of("&7사망 시 사이즈 4 슬라임 2마리"));
		unitDescriptions.put("charged_creeper", java.util.List.of("&7천둥 조건 전직 결과"));
		unitDescriptions.put("piglin", java.util.List.of("&750% 확률로 좀비 피글린 생성"));
		unitDescriptions.put("zombified_piglin", java.util.List.of("&7주변 아군 강화"));
		unitDescriptions.put("blaze", java.util.List.of("&7작은 화염구 3연사"));
		unitDescriptions.put("enderman", java.util.List.of("&7스킬 사용 시 다음 라인 아군 소환 위치로 순간이동", "&7공격력 +8, 공격속도 -7"));
		unitDescriptions.put("piglin_brute", java.util.List.of("&7자가 강화 폭발력"));
	}

	public void normalize() {
		var defaults = new TextConfigFile();
		prefix = value(prefix, defaults.prefix);
		bossBarTemplate = value(bossBarTemplate, defaults.bossBarTemplate);
		if (LEGACY_BOSS_BAR_TEMPLATE.equals(bossBarTemplate)) {
			bossBarTemplate = defaults.bossBarTemplate;
		}
		bossBarTitle = value(bossBarTitle, defaults.bossBarTitle);
		teamChatFormat = value(teamChatFormat, defaults.teamChatFormat);
		teamChatNoTeamMessage = value(teamChatNoTeamMessage, defaults.teamChatNoTeamMessage);
		teamChatEmptyMessage = value(teamChatEmptyMessage, defaults.teamChatEmptyMessage);
		factionSelectBossBarTemplate = value(factionSelectBossBarTemplate, defaults.factionSelectBossBarTemplate);
		closedLaneMessage = value(closedLaneMessage, defaults.closedLaneMessage);
		ladderPrefixFormat = value(ladderPrefixFormat, defaults.ladderPrefixFormat);
		captainStar = value(captainStar, defaults.captainStar);
		unitHudTemplate = value(unitHudTemplate, defaults.unitHudTemplate);
		unitHudReadyMessage = value(unitHudReadyMessage, defaults.unitHudReadyMessage);
		unitHudCooldownTemplate = value(unitHudCooldownTemplate, defaults.unitHudCooldownTemplate);
		unitHudFallbackSkillName = value(unitHudFallbackSkillName, defaults.unitHudFallbackSkillName);
		unitHudUnknownUnitName = value(unitHudUnknownUnitName, defaults.unitHudUnknownUnitName);
		captainHudTemplate = value(captainHudTemplate, defaults.captainHudTemplate);
		if (LEGACY_CAPTAIN_HUD_TEMPLATE.equals(captainHudTemplate)) {
			captainHudTemplate = defaults.captainHudTemplate;
		}
		captainHudNoTargetPlayerName = value(captainHudNoTargetPlayerName, defaults.captainHudNoTargetPlayerName);
		spectatorQueueHudTemplate = value(spectatorQueueHudTemplate, defaults.spectatorQueueHudTemplate);
		captureDefaultBossBarText = value(captureDefaultBossBarText, defaults.captureDefaultBossBarText);
		captureContestedBossBarText = value(captureContestedBossBarText, defaults.captureContestedBossBarText);
		captureRedOwnerBossBarText = value(captureRedOwnerBossBarText, defaults.captureRedOwnerBossBarText);
		captureBlueOwnerBossBarText = value(captureBlueOwnerBossBarText, defaults.captureBlueOwnerBossBarText);
		captureNeutralOwnerBossBarText = value(captureNeutralOwnerBossBarText, defaults.captureNeutralOwnerBossBarText);
		captureProgressBossBarTemplate = value(captureProgressBossBarTemplate, defaults.captureProgressBossBarTemplate);
		captureOwnerChangedBroadcastTemplate = value(captureOwnerChangedBroadcastTemplate, defaults.captureOwnerChangedBroadcastTemplate);
		captureLane1Name = value(captureLane1Name, defaults.captureLane1Name);
		captureLane2Name = value(captureLane2Name, defaults.captureLane2Name);
		captureLane3Name = value(captureLane3Name, defaults.captureLane3Name);
		captureOwnerRedName = value(captureOwnerRedName, defaults.captureOwnerRedName);
		captureOwnerBlueName = value(captureOwnerBlueName, defaults.captureOwnerBlueName);
		captureOwnerNeutralName = value(captureOwnerNeutralName, defaults.captureOwnerNeutralName);
		lobbyPhaseMessage = value(lobbyPhaseMessage, defaults.lobbyPhaseMessage);
		teamSelectPhaseMessage = value(teamSelectPhaseMessage, defaults.teamSelectPhaseMessage);
		factionSelectPhaseMessage = value(factionSelectPhaseMessage, defaults.factionSelectPhaseMessage);
		gameStartPhaseMessage = value(gameStartPhaseMessage, defaults.gameStartPhaseMessage);
		gameRunningPhaseMessage = value(gameRunningPhaseMessage, defaults.gameRunningPhaseMessage);
		gameEndPhaseMessage = value(gameEndPhaseMessage, defaults.gameEndPhaseMessage);
		factionSelectionMessage = value(factionSelectionMessage, defaults.factionSelectionMessage);
		villagerFactionName = value(villagerFactionName, defaults.villagerFactionName);
		monsterFactionName = value(monsterFactionName, defaults.monsterFactionName);
		netherFactionName = value(netherFactionName, defaults.netherFactionName);
		advanceNotAvailableMessage = value(advanceNotAvailableMessage, defaults.advanceNotAvailableMessage);
		advanceReadyMessage = value(advanceReadyMessage, defaults.advanceReadyMessage);
		gameEndTitleTemplate = value(gameEndTitleTemplate, defaults.gameEndTitleTemplate);
		gameEndDrawTitleTemplate = value(gameEndDrawTitleTemplate, defaults.gameEndDrawTitleTemplate);
		captainSpawnGuiTitle = value(captainSpawnGuiTitle, defaults.captainSpawnGuiTitle);
		captainSpawnNoFactionMessage = value(captainSpawnNoFactionMessage, defaults.captainSpawnNoFactionMessage);
		captainSpawnBlockedLaneMessage = value(captainSpawnBlockedLaneMessage, defaults.captainSpawnBlockedLaneMessage);
		gameStartCountdownTitle = value(gameStartCountdownTitle, defaults.gameStartCountdownTitle);
		gameStartCountdownSubtitleTemplate = value(gameStartCountdownSubtitleTemplate, defaults.gameStartCountdownSubtitleTemplate);
		victoryCountdownSubtitleTemplate = value(victoryCountdownSubtitleTemplate, defaults.victoryCountdownSubtitleTemplate);
		customDeathMessage = value(customDeathMessage, defaults.customDeathMessage);
		customDeathMessageWithAttacker = value(customDeathMessageWithAttacker, defaults.customDeathMessageWithAttacker);
		autoStartEnabledMessage = value(autoStartEnabledMessage, defaults.autoStartEnabledMessage);
		autoStartDisabledMessage = value(autoStartDisabledMessage, defaults.autoStartDisabledMessage);
		mainLobbyTitle = value(mainLobbyTitle, defaults.mainLobbyTitle);
		mainLobbyCaptainPreferenceName = value(mainLobbyCaptainPreferenceName, defaults.mainLobbyCaptainPreferenceName);
		mainLobbyCaptainPreferenceLore = listValue(mainLobbyCaptainPreferenceLore, defaults.mainLobbyCaptainPreferenceLore);
		mainLobbyCaptainPreferenceEnabledLore = value(mainLobbyCaptainPreferenceEnabledLore, defaults.mainLobbyCaptainPreferenceEnabledLore);
		mainLobbyCaptainPreferenceDisabledLore = value(mainLobbyCaptainPreferenceDisabledLore, defaults.mainLobbyCaptainPreferenceDisabledLore);
		mainLobbyStatsName = value(mainLobbyStatsName, defaults.mainLobbyStatsName);
		mainLobbyStatsLore = listValue(mainLobbyStatsLore, defaults.mainLobbyStatsLore);
		mainLobbyRulesName = value(mainLobbyRulesName, defaults.mainLobbyRulesName);
		mainLobbyRulesLore = listValue(mainLobbyRulesLore, defaults.mainLobbyRulesLore);
		mainLobbyUnitGuideName = value(mainLobbyUnitGuideName, defaults.mainLobbyUnitGuideName);
		mainLobbyUnitGuideLore = listValue(mainLobbyUnitGuideLore, defaults.mainLobbyUnitGuideLore);
		mainLobbyBiomeGuideName = value(mainLobbyBiomeGuideName, defaults.mainLobbyBiomeGuideName);
		mainLobbyBiomeGuideLore = listValue(mainLobbyBiomeGuideLore, defaults.mainLobbyBiomeGuideLore);
		mainLobbyAdminToolsName = value(mainLobbyAdminToolsName, defaults.mainLobbyAdminToolsName);
		mainLobbyCloseName = value(mainLobbyCloseName, defaults.mainLobbyCloseName);
		adminToolsGuiTitle = value(adminToolsGuiTitle, defaults.adminToolsGuiTitle);
		adminToolsAssignTeamsName = value(adminToolsAssignTeamsName, defaults.adminToolsAssignTeamsName);
		adminToolsClearTeamsName = value(adminToolsClearTeamsName, defaults.adminToolsClearTeamsName);
		adminToolsFactionSelectName = value(adminToolsFactionSelectName, defaults.adminToolsFactionSelectName);
		adminToolsGameEndName = value(adminToolsGameEndName, defaults.adminToolsGameEndName);
		adminToolsCloseName = value(adminToolsCloseName, defaults.adminToolsCloseName);
		adminToolsFactionSelectBlockedMessage = value(adminToolsFactionSelectBlockedMessage, defaults.adminToolsFactionSelectBlockedMessage);
		lobbyScoreboardTitle = value(lobbyScoreboardTitle, defaults.lobbyScoreboardTitle);
		lobbyScoreboardPhaseTemplate = value(lobbyScoreboardPhaseTemplate, defaults.lobbyScoreboardPhaseTemplate);
		lobbyScoreboardPlayerTemplate = value(lobbyScoreboardPlayerTemplate, defaults.lobbyScoreboardPlayerTemplate);
		lobbyScoreboardWikiHint = value(lobbyScoreboardWikiHint, defaults.lobbyScoreboardWikiHint);
		wikiMainTitle = value(wikiMainTitle, defaults.wikiMainTitle);
		wikiOverviewName = value(wikiOverviewName, defaults.wikiOverviewName);
		wikiOverviewLore = listValue(wikiOverviewLore, defaults.wikiOverviewLore);
		wikiCommanderName = value(wikiCommanderName, defaults.wikiCommanderName);
		wikiCommanderLore = listValue(wikiCommanderLore, defaults.wikiCommanderLore);
		wikiOverviewPhaseLoreTemplate = value(wikiOverviewPhaseLoreTemplate, defaults.wikiOverviewPhaseLoreTemplate);
		wikiOverviewRuleLore = value(wikiOverviewRuleLore, defaults.wikiOverviewRuleLore);
		wikiOverviewHintLore = value(wikiOverviewHintLore, defaults.wikiOverviewHintLore);
		wikiFactionButtonName = value(wikiFactionButtonName, defaults.wikiFactionButtonName);
		wikiFactionButtonLore = listValue(wikiFactionButtonLore, defaults.wikiFactionButtonLore);
		wikiFactionButtonLore1 = value(wikiFactionButtonLore1, defaults.wikiFactionButtonLore1);
		wikiFactionButtonLore2 = value(wikiFactionButtonLore2, defaults.wikiFactionButtonLore2);
		wikiUnitButtonName = value(wikiUnitButtonName, defaults.wikiUnitButtonName);
		wikiUnitButtonLore = listValue(wikiUnitButtonLore, defaults.wikiUnitButtonLore);
		wikiUnitButtonLore1 = value(wikiUnitButtonLore1, defaults.wikiUnitButtonLore1);
		wikiUnitButtonLore2 = value(wikiUnitButtonLore2, defaults.wikiUnitButtonLore2);
		wikiBiomeButtonName = value(wikiBiomeButtonName, defaults.wikiBiomeButtonName);
		wikiBiomeButtonLore = listValue(wikiBiomeButtonLore, defaults.wikiBiomeButtonLore);
		wikiBiomeButtonLore1 = value(wikiBiomeButtonLore1, defaults.wikiBiomeButtonLore1);
		wikiBiomeButtonLore2 = value(wikiBiomeButtonLore2, defaults.wikiBiomeButtonLore2);
		wikiFactionIndexTitle = value(wikiFactionIndexTitle, defaults.wikiFactionIndexTitle);
		wikiUnitIndexTitle = value(wikiUnitIndexTitle, defaults.wikiUnitIndexTitle);
		wikiBiomeIndexTitle = value(wikiBiomeIndexTitle, defaults.wikiBiomeIndexTitle);
		wikiFactionUnitListTitleTemplate = value(wikiFactionUnitListTitleTemplate, defaults.wikiFactionUnitListTitleTemplate);
		wikiSummaryName = value(wikiSummaryName, defaults.wikiSummaryName);
		wikiBackName = value(wikiBackName, defaults.wikiBackName);
		wikiBackFactionLore = value(wikiBackFactionLore, defaults.wikiBackFactionLore);
		wikiBackUnitFactionLore = value(wikiBackUnitFactionLore, defaults.wikiBackUnitFactionLore);
		wikiBackUnitListLore = value(wikiBackUnitListLore, defaults.wikiBackUnitListLore);
		wikiBackBiomeLore = value(wikiBackBiomeLore, defaults.wikiBackBiomeLore);
		wikiHomeName = value(wikiHomeName, defaults.wikiHomeName);
		wikiHomeLore = value(wikiHomeLore, defaults.wikiHomeLore);
		wikiNoDataLore = value(wikiNoDataLore, defaults.wikiNoDataLore);
		wikiVillagerCategoryName = value(wikiVillagerCategoryName, defaults.wikiVillagerCategoryName);
		wikiVillagerCategoryLore = value(wikiVillagerCategoryLore, defaults.wikiVillagerCategoryLore);
		wikiMonsterCategoryName = value(wikiMonsterCategoryName, defaults.wikiMonsterCategoryName);
		wikiMonsterCategoryLore = value(wikiMonsterCategoryLore, defaults.wikiMonsterCategoryLore);
		wikiNetherCategoryName = value(wikiNetherCategoryName, defaults.wikiNetherCategoryName);
		wikiNetherCategoryLore = value(wikiNetherCategoryLore, defaults.wikiNetherCategoryLore);
		preparationGuiTitle = value(preparationGuiTitle, defaults.preparationGuiTitle);
		preparationToggleLore = value(preparationToggleLore, defaults.preparationToggleLore);
		preparationReadonlyLore = value(preparationReadonlyLore, defaults.preparationReadonlyLore);
		preparationCostLoreTemplate = value(preparationCostLoreTemplate, defaults.preparationCostLoreTemplate);
		preparationSelectedLore = value(preparationSelectedLore, defaults.preparationSelectedLore);
		preparationUnselectedLore = value(preparationUnselectedLore, defaults.preparationUnselectedLore);
		advanceGuiTitle = value(advanceGuiTitle, defaults.advanceGuiTitle);
		advanceNoOptionName = value(advanceNoOptionName, defaults.advanceNoOptionName);
		advanceNoOptionLore = value(advanceNoOptionLore, defaults.advanceNoOptionLore);
		advanceConditionPrefix = value(advanceConditionPrefix, defaults.advanceConditionPrefix);
		advanceConditionBiomeDurationLoreTemplate = value(advanceConditionBiomeDurationLoreTemplate, defaults.advanceConditionBiomeDurationLoreTemplate);
		advanceConditionBiomeWeatherDurationLoreTemplate = value(advanceConditionBiomeWeatherDurationLoreTemplate, defaults.advanceConditionBiomeWeatherDurationLoreTemplate);
		advanceConditionWeatherDurationLoreTemplate = value(advanceConditionWeatherDurationLoreTemplate, defaults.advanceConditionWeatherDurationLoreTemplate);
		advanceConditionBiomeDurationSuffixTemplate = value(advanceConditionBiomeDurationSuffixTemplate, defaults.advanceConditionBiomeDurationSuffixTemplate);
		advanceConditionBiomeWeatherDurationSuffixTemplate = value(advanceConditionBiomeWeatherDurationSuffixTemplate, defaults.advanceConditionBiomeWeatherDurationSuffixTemplate);
		advanceProgressLoreTemplate = value(advanceProgressLoreTemplate, defaults.advanceProgressLoreTemplate);
		advanceConditionUnmetLore = value(advanceConditionUnmetLore, defaults.advanceConditionUnmetLore);
		advanceWaitingLore = value(advanceWaitingLore, defaults.advanceWaitingLore);
		advanceClickLore = value(advanceClickLore, defaults.advanceClickLore);
		advanceBroadcastMessage = value(advanceBroadcastMessage, defaults.advanceBroadcastMessage);
		advanceCompleteMessage = value(advanceCompleteMessage, defaults.advanceCompleteMessage);
		unitSpawnedMessage = value(unitSpawnedMessage, defaults.unitSpawnedMessage);
		unitSpawnCaptainOnlyMessage = value(unitSpawnCaptainOnlyMessage, defaults.unitSpawnCaptainOnlyMessage);
		unitSpawnUnknownUnitMessage = value(unitSpawnUnknownUnitMessage, defaults.unitSpawnUnknownUnitMessage);
		unitSpawnWrongFactionMessage = value(unitSpawnWrongFactionMessage, defaults.unitSpawnWrongFactionMessage);
		unitSpawnNoCandidateMessage = value(unitSpawnNoCandidateMessage, defaults.unitSpawnNoCandidateMessage);
		unitSpawnInsufficientManaMessage = value(unitSpawnInsufficientManaMessage, defaults.unitSpawnInsufficientManaMessage);
		unitSpawnTargetMissingMessage = value(unitSpawnTargetMissingMessage, defaults.unitSpawnTargetMissingMessage);
		captainSpawnSuccessMessage = value(captainSpawnSuccessMessage, defaults.captainSpawnSuccessMessage);
		captainSpawnCostLoreTemplate = value(captainSpawnCostLoreTemplate, defaults.captainSpawnCostLoreTemplate);
		captainSpawnCooldownLoreTemplate = value(captainSpawnCooldownLoreTemplate, defaults.captainSpawnCooldownLoreTemplate);
		captainSpawnHealthLoreTemplate = value(captainSpawnHealthLoreTemplate, defaults.captainSpawnHealthLoreTemplate);
		captainSpawnReadyLore = value(captainSpawnReadyLore, defaults.captainSpawnReadyLore);
		captainSpawnBlockedLore = value(captainSpawnBlockedLore, defaults.captainSpawnBlockedLore);
		factionSelectionRedTitle = value(factionSelectionRedTitle, defaults.factionSelectionRedTitle);
		factionSelectionBlueTitle = value(factionSelectionBlueTitle, defaults.factionSelectionBlueTitle);
		factionSelectionCaptainSkillLoreTemplate = value(factionSelectionCaptainSkillLoreTemplate, defaults.factionSelectionCaptainSkillLoreTemplate);
		factionSelectionSelectedLore = value(factionSelectionSelectedLore, defaults.factionSelectionSelectedLore);
		factionSelectionClickLore = value(factionSelectionClickLore, defaults.factionSelectionClickLore);
		tradePurchaseSuccessMessage = value(tradePurchaseSuccessMessage, defaults.tradePurchaseSuccessMessage);
		tradeInsufficientFundsMessage = value(tradeInsufficientFundsMessage, defaults.tradeInsufficientFundsMessage);
		tradeInventoryFullMessage = value(tradeInventoryFullMessage, defaults.tradeInventoryFullMessage);
		tradeInvalidEntryMessage = value(tradeInvalidEntryMessage, defaults.tradeInvalidEntryMessage);
		tradeUnsupportedFactionMessage = value(tradeUnsupportedFactionMessage, defaults.tradeUnsupportedFactionMessage);
		tradeVillagerTitle = value(tradeVillagerTitle, defaults.tradeVillagerTitle);
		tradeVillagerEnchantTitle = value(tradeVillagerEnchantTitle, defaults.tradeVillagerEnchantTitle);
		tradeNetherTitle = value(tradeNetherTitle, defaults.tradeNetherTitle);
		tradePriceLoreTemplate = value(tradePriceLoreTemplate, defaults.tradePriceLoreTemplate);
		tradeClickLore = value(tradeClickLore, defaults.tradeClickLore);
		tradeMaxLevelMessage = value(tradeMaxLevelMessage, defaults.tradeMaxLevelMessage);
		tradeNoEligibleEquipmentMessage = value(tradeNoEligibleEquipmentMessage, defaults.tradeNoEligibleEquipmentMessage);
		tradeEnchantTargetLoreTemplate = value(tradeEnchantTargetLoreTemplate, defaults.tradeEnchantTargetLoreTemplate);
		tradeEnchantCurrentLoreTemplate = value(tradeEnchantCurrentLoreTemplate, defaults.tradeEnchantCurrentLoreTemplate);
		tradeEnchantNextLoreTemplate = value(tradeEnchantNextLoreTemplate, defaults.tradeEnchantNextLoreTemplate);
		tradeEnchantMaxLore = value(tradeEnchantMaxLore, defaults.tradeEnchantMaxLore);
		captainMenuItemName = value(captainMenuItemName, defaults.captainMenuItemName);
		captainMenuItemUseLore = value(captainMenuItemUseLore, defaults.captainMenuItemUseLore);
		captainMenuItemFactionLoreTemplate = value(captainMenuItemFactionLoreTemplate, defaults.captainMenuItemFactionLoreTemplate);
		captainSkillItemName = value(captainSkillItemName, defaults.captainSkillItemName);
		captainSkillItemUseLore = value(captainSkillItemUseLore, defaults.captainSkillItemUseLore);
		captainSkillItemFactionLoreTemplate = value(captainSkillItemFactionLoreTemplate, defaults.captainSkillItemFactionLoreTemplate);
		captainSkillCooldownMessage = value(captainSkillCooldownMessage, defaults.captainSkillCooldownMessage);
		captainSkillActivatedMessage = value(captainSkillActivatedMessage, defaults.captainSkillActivatedMessage);
		captainSkillInsufficientManaMessage = value(captainSkillInsufficientManaMessage, defaults.captainSkillInsufficientManaMessage);
		captainVillagerSuccessMessage = value(captainVillagerSuccessMessage, defaults.captainVillagerSuccessMessage);
		captainVillagerNoTargetMessage = value(captainVillagerNoTargetMessage, defaults.captainVillagerNoTargetMessage);
		captainMonsterWeatherGuiTitle = value(captainMonsterWeatherGuiTitle, defaults.captainMonsterWeatherGuiTitle);
		captainMonsterWeatherClearName = value(captainMonsterWeatherClearName, defaults.captainMonsterWeatherClearName);
		captainMonsterWeatherRainName = value(captainMonsterWeatherRainName, defaults.captainMonsterWeatherRainName);
		captainMonsterWeatherThunderName = value(captainMonsterWeatherThunderName, defaults.captainMonsterWeatherThunderName);
		captainMonsterWeatherClearLore = value(captainMonsterWeatherClearLore, defaults.captainMonsterWeatherClearLore);
		captainMonsterWeatherRainLore = value(captainMonsterWeatherRainLore, defaults.captainMonsterWeatherRainLore);
		captainMonsterWeatherThunderLore = value(captainMonsterWeatherThunderLore, defaults.captainMonsterWeatherThunderLore);
		captainMonsterWeatherRemainingLoreTemplate = value(captainMonsterWeatherRemainingLoreTemplate, defaults.captainMonsterWeatherRemainingLoreTemplate);
		captainMonsterWeatherPersistentLore = value(captainMonsterWeatherPersistentLore, defaults.captainMonsterWeatherPersistentLore);
		captainMonsterWeatherActiveLore = value(captainMonsterWeatherActiveLore, defaults.captainMonsterWeatherActiveLore);
		captainMonsterWeatherClickLore = value(captainMonsterWeatherClickLore, defaults.captainMonsterWeatherClickLore);
		captainMonsterWeatherSuccessMessage = value(captainMonsterWeatherSuccessMessage, defaults.captainMonsterWeatherSuccessMessage);
		captainNetherPortalSuccessMessage = value(captainNetherPortalSuccessMessage, defaults.captainNetherPortalSuccessMessage);
		captainPortalRefundMessage = value(captainPortalRefundMessage, defaults.captainPortalRefundMessage);
		adminForceUnitMessage = value(adminForceUnitMessage, defaults.adminForceUnitMessage);
		adminBotsSuccessMessage = value(adminBotsSuccessMessage, defaults.adminBotsSuccessMessage);
		adminBotsPartialMessage = value(adminBotsPartialMessage, defaults.adminBotsPartialMessage);
		adminBotsInvalidCountMessage = value(adminBotsInvalidCountMessage, defaults.adminBotsInvalidCountMessage);
		commandRootReadyMessage = value(commandRootReadyMessage, defaults.commandRootReadyMessage);
		commandReloadMessage = value(commandReloadMessage, defaults.commandReloadMessage);
		commandSourceNotFoundMessage = value(commandSourceNotFoundMessage, defaults.commandSourceNotFoundMessage);
		commandPlayerNotFoundMessage = value(commandPlayerNotFoundMessage, defaults.commandPlayerNotFoundMessage);
		commandPreferenceUpdatedMessage = value(commandPreferenceUpdatedMessage, defaults.commandPreferenceUpdatedMessage);
		commandAssignCaptainMessage = value(commandAssignCaptainMessage, defaults.commandAssignCaptainMessage);
		commandTeamSelectionMessage = value(commandTeamSelectionMessage, defaults.commandTeamSelectionMessage);
		commandForceStartMessage = value(commandForceStartMessage, defaults.commandForceStartMessage);
		commandPhaseChangedMessage = value(commandPhaseChangedMessage, defaults.commandPhaseChangedMessage);
		commandLaneStateMessage = value(commandLaneStateMessage, defaults.commandLaneStateMessage);
		commandForceUnitSuccessMessage = value(commandForceUnitSuccessMessage, defaults.commandForceUnitSuccessMessage);
		commandPlaceNearestPlayerOnlyMessage = value(commandPlaceNearestPlayerOnlyMessage, defaults.commandPlaceNearestPlayerOnlyMessage);
		commandPlaceNearestNoBiomeMessage = value(commandPlaceNearestNoBiomeMessage, defaults.commandPlaceNearestNoBiomeMessage);
		commandPlaceNearestMissingStructureMessage = value(commandPlaceNearestMissingStructureMessage, defaults.commandPlaceNearestMissingStructureMessage);
		commandPlaceNearestSuccessMessage = value(commandPlaceNearestSuccessMessage, defaults.commandPlaceNearestSuccessMessage);
		commandPlaceNearestFailureMessage = value(commandPlaceNearestFailureMessage, defaults.commandPlaceNearestFailureMessage);
		commandServerNotBoundMessage = value(commandServerNotBoundMessage, defaults.commandServerNotBoundMessage);
		commandResetStructuresSuccessMessage = value(commandResetStructuresSuccessMessage, defaults.commandResetStructuresSuccessMessage);
		commandResetStructuresPartialMessage = value(commandResetStructuresPartialMessage, defaults.commandResetStructuresPartialMessage);
		commandChargeManaFailedMessage = value(commandChargeManaFailedMessage, defaults.commandChargeManaFailedMessage);
		commandChargeManaSuccessMessage = value(commandChargeManaSuccessMessage, defaults.commandChargeManaSuccessMessage);
		commandCaptainSkillFailedMessage = value(commandCaptainSkillFailedMessage, defaults.commandCaptainSkillFailedMessage);
		commandCaptainSkillSuccessMessage = value(commandCaptainSkillSuccessMessage, defaults.commandCaptainSkillSuccessMessage);
		commandAdvanceFailedMessage = value(commandAdvanceFailedMessage, defaults.commandAdvanceFailedMessage);
		commandAdvanceSuccessMessage = value(commandAdvanceSuccessMessage, defaults.commandAdvanceSuccessMessage);
		commandOpenGuiPlayerOnlyMessage = value(commandOpenGuiPlayerOnlyMessage, defaults.commandOpenGuiPlayerOnlyMessage);
		commandOpenMainSuccessMessage = value(commandOpenMainSuccessMessage, defaults.commandOpenMainSuccessMessage);
		commandOpenWikiSuccessMessage = value(commandOpenWikiSuccessMessage, defaults.commandOpenWikiSuccessMessage);
		commandOpenUnitIndexSuccessMessage = value(commandOpenUnitIndexSuccessMessage, defaults.commandOpenUnitIndexSuccessMessage);
		commandOpenBiomeIndexSuccessMessage = value(commandOpenBiomeIndexSuccessMessage, defaults.commandOpenBiomeIndexSuccessMessage);
		commandOpenAdminToolsSuccessMessage = value(commandOpenAdminToolsSuccessMessage, defaults.commandOpenAdminToolsSuccessMessage);
		commandOpenFactionSuccessMessage = value(commandOpenFactionSuccessMessage, defaults.commandOpenFactionSuccessMessage);
		commandOpenPreparationSuccessMessage = value(commandOpenPreparationSuccessMessage, defaults.commandOpenPreparationSuccessMessage);
		commandOpenCaptainSpawnSuccessMessage = value(commandOpenCaptainSpawnSuccessMessage, defaults.commandOpenCaptainSpawnSuccessMessage);
		commandOpenTradeSuccessMessage = value(commandOpenTradeSuccessMessage, defaults.commandOpenTradeSuccessMessage);
		commandOpenAdvanceSuccessMessage = value(commandOpenAdvanceSuccessMessage, defaults.commandOpenAdvanceSuccessMessage);
		commandUnsupportedGuiMessage = value(commandUnsupportedGuiMessage, defaults.commandUnsupportedGuiMessage);
		commandClearTeamsMessage = value(commandClearTeamsMessage, defaults.commandClearTeamsMessage);
		commandTimeAdjustedMessage = value(commandTimeAdjustedMessage, defaults.commandTimeAdjustedMessage);
		commandStatPlayerTemplate = value(commandStatPlayerTemplate, defaults.commandStatPlayerTemplate);
		commandStatLadderTemplate = value(commandStatLadderTemplate, defaults.commandStatLadderTemplate);
		commandStatCombatTemplate = value(commandStatCombatTemplate, defaults.commandStatCombatTemplate);
		commandStatCurrencyTemplate = value(commandStatCurrencyTemplate, defaults.commandStatCurrencyTemplate);
		midMatchJoinAvailableMessage = value(midMatchJoinAvailableMessage, defaults.midMatchJoinAvailableMessage);
		midMatchJoinUnavailableMessage = value(midMatchJoinUnavailableMessage, defaults.midMatchJoinUnavailableMessage);
		midMatchJoinAlreadyJoinedMessage = value(midMatchJoinAlreadyJoinedMessage, defaults.midMatchJoinAlreadyJoinedMessage);
		midMatchJoinSuccessMessage = value(midMatchJoinSuccessMessage, defaults.midMatchJoinSuccessMessage);
		surrenderVoteUnavailableMessage = value(surrenderVoteUnavailableMessage, defaults.surrenderVoteUnavailableMessage);
		surrenderVoteNoTeamMessage = value(surrenderVoteNoTeamMessage, defaults.surrenderVoteNoTeamMessage);
		surrenderVoteDuplicateMessage = value(surrenderVoteDuplicateMessage, defaults.surrenderVoteDuplicateMessage);
		surrenderVoteProgressMessage = value(surrenderVoteProgressMessage, defaults.surrenderVoteProgressMessage);
		environmentAttackerName = value(environmentAttackerName, defaults.environmentAttackerName);
		creeperSelfDestructPrimedMessage = value(creeperSelfDestructPrimedMessage, defaults.creeperSelfDestructPrimedMessage);
		runningSidebarLaneTemplate = value(runningSidebarLaneTemplate, defaults.runningSidebarLaneTemplate);
		runningSidebarHiddenBiomeName = value(runningSidebarHiddenBiomeName, defaults.runningSidebarHiddenBiomeName);
		runningSidebarNeutralIcon = value(runningSidebarNeutralIcon, defaults.runningSidebarNeutralIcon);
		runningSidebarContestedIcon = value(runningSidebarContestedIcon, defaults.runningSidebarContestedIcon);
		runningSidebarRedIcon = value(runningSidebarRedIcon, defaults.runningSidebarRedIcon);
		runningSidebarBlueIcon = value(runningSidebarBlueIcon, defaults.runningSidebarBlueIcon);
		if (factionSummaries.isEmpty() && defaults.factionSummaries != null) factionSummaries.putAll(defaults.factionSummaries);
		if (captainSkillDescriptions.isEmpty() && defaults.captainSkillDescriptions != null) captainSkillDescriptions.putAll(defaults.captainSkillDescriptions);
		if (unitDescriptions.isEmpty() && defaults.unitDescriptions != null) unitDescriptions.putAll(defaults.unitDescriptions);
	}

	public void applyTo(SystemConfig systemConfig) {
		if (systemConfig == null) {
			return;
		}
		systemConfig.prefix = prefix;
		systemConfig.bossBar.template = bossBarTemplate;
		systemConfig.teamChat.format = teamChatFormat;
		systemConfig.teamChat.noTeamMessage = teamChatNoTeamMessage;
		systemConfig.teamChat.emptyMessage = teamChatEmptyMessage;
		systemConfig.lobby.factionSelectBossBarTemplate = factionSelectBossBarTemplate;
		systemConfig.inGame.closedLaneMessage = closedLaneMessage;
		systemConfig.display.ladderPrefixFormat = ladderPrefixFormat;
		systemConfig.display.captainStar = captainStar;
		systemConfig.display.unitHudTemplate = unitHudTemplate;
		systemConfig.display.unitHudReadyMessage = unitHudReadyMessage;
		systemConfig.display.unitHudFallbackSkillName = unitHudFallbackSkillName;
		systemConfig.display.unitHudUnknownUnitName = unitHudUnknownUnitName;
		systemConfig.display.captainHudTemplate = captainHudTemplate;
		systemConfig.display.captainHudNoTargetPlayerName = captainHudNoTargetPlayerName;
		systemConfig.display.spectatorQueueHudTemplate = spectatorQueueHudTemplate;
		systemConfig.capture.defaultBossBarText = captureDefaultBossBarText;
		systemConfig.capture.contestedBossBarText = captureContestedBossBarText;
		systemConfig.capture.redOwnerBossBarText = captureRedOwnerBossBarText;
		systemConfig.capture.blueOwnerBossBarText = captureBlueOwnerBossBarText;
		systemConfig.capture.neutralOwnerBossBarText = captureNeutralOwnerBossBarText;
		systemConfig.capture.captureProgressBossBarTemplate = captureProgressBossBarTemplate;
		systemConfig.announcements.lobbyPhaseMessage = lobbyPhaseMessage;
		systemConfig.announcements.teamSelectPhaseMessage = teamSelectPhaseMessage;
		systemConfig.announcements.factionSelectPhaseMessage = factionSelectPhaseMessage;
		systemConfig.announcements.gameStartPhaseMessage = gameStartPhaseMessage;
		systemConfig.announcements.gameRunningPhaseMessage = gameRunningPhaseMessage;
		systemConfig.announcements.gameEndPhaseMessage = gameEndPhaseMessage;
		systemConfig.announcements.factionSelectionMessage = factionSelectionMessage;
		systemConfig.announcements.villagerFactionName = villagerFactionName;
		systemConfig.announcements.monsterFactionName = monsterFactionName;
		systemConfig.announcements.netherFactionName = netherFactionName;
		systemConfig.announcements.customDeathMessage = customDeathMessage;
		systemConfig.announcements.customDeathMessageWithAttacker = customDeathMessageWithAttacker;
		systemConfig.announcements.autoStartEnabledMessage = autoStartEnabledMessage;
		systemConfig.announcements.autoStartDisabledMessage = autoStartDisabledMessage;
		systemConfig.advance.notAvailableMessage = advanceNotAvailableMessage;
		systemConfig.advance.readyMessage = advanceReadyMessage;
		systemConfig.gameEnd.titleTemplate = gameEndTitleTemplate;
		systemConfig.gameEnd.drawTitleTemplate = gameEndDrawTitleTemplate;
		systemConfig.gameEnd.victoryCountdownSubtitleTemplate = victoryCountdownSubtitleTemplate;
		systemConfig.gameStart.captainSpawnGuiTitle = captainSpawnGuiTitle;
		systemConfig.gameStart.captainSpawnNoFactionMessage = captainSpawnNoFactionMessage;
		systemConfig.gameStart.captainSpawnBlockedLaneMessage = captainSpawnBlockedLaneMessage;
		systemConfig.gameStart.countdownTitle = gameStartCountdownTitle;
		systemConfig.gameStart.countdownSubtitleTemplate = gameStartCountdownSubtitleTemplate;
	}

	private String value(String current, String fallback) {
		return current == null || current.isBlank() ? fallback : current;
	}

	private List<String> listValue(List<String> current, List<String> fallback) {
		return current == null || current.isEmpty() ? fallback : current;
	}
}
